# Scruitinizer WordPress PLugin Profile
# Profile: WP-Plugins_0.9
filter:
    excluded_paths: 
        - libs/*
        - assets/jquery-scrolldepth/*
tools:
    # Runs the JSHint static analysis tool (https://scrutinizer-ci.com/docs/tools/javascript/jshint/)
    js_hint: true

    # Runs PHP Code Sniffer
    php_code_sniffer:
        config:
            standard: WordPress

    # Runs the PHP CS Fixer (http://cs.sensiolabs.org/) (https://scrutinizer-ci.com/docs/tools/php/cs-fixer/)
    # php_cs_fixer:
    #    config: { level: psr2 }

    # PHPLOC - PHP Lines of code
    php_loc: true

    # SensioLabs Security Checker (https://scrutinizer-ci.com/docs/tools/php/security-advisory-checker/)
    sensiolabs_security_checker: true

    # PHP Copy/Paste Detector (https://scrutinizer-ci.com/docs/tools/php/copy-paste-detector/)
    php_cpd: true

    # PHP PDepend (https://scrutinizer-ci.com/docs/tools/php/pdepend/)
    # Analyzes the size and structure of a PHP project
    php_pdepend: true

    # PHP Analyzer (https://scrutinizer-ci.com/docs/tools/php/php-analyzer/)
    php_analyzer: true

    # External Code Coverage (https://scrutinizer-ci.com/docs/tools/external-code-coverage/)
    # external_code_coverage: true

#checks:
#    php:
#        newline_at_end_of_file: true
#        prefer_unix_line_ending: true
#        avoid_closing_tag: true
#        no_trailing_whitespace: true